### ISSUE TITLE
OBJ_LOP and  OBJ_LOPCamera compilation error

### ISSUE THREAD

**Issue by AlexSchwank** [sideeffects/HoudiniUsdBridge#7]
When I try to compile _master_ I'm running into this error:

```
/XXX/houdiniusdbridge/src/houdini/custom/USDOP/OBJ_LOPCamera.C: In static member function ‘static PRM_Template* pxrInternal_v0_19__pxrReserved__::OBJ_LOPCamera::getTemplateList()’:
/XXX/houdiniusdbridge/src/houdini/custom/USDOP/OBJ_LOPCamera.C:96:54: error: ‘lopPathName’ was not declared in this scope
  PRM_Template(PRM_STRING, PRM_TYPE_DYNAMIC_PATH, 1, &lopPathName,
                                                      ^~~~~~~~~~~
/XXX/houdiniusdbridge/src/houdini/custom/USDOP/OBJ_LOPCamera.C:100:18: error: ‘lopPrimPathDialogSpareData’ was not declared in this scope
        0, 0, 0, &lopPrimPathDialogSpareData),
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/XXX/houdiniusdbridge/src/houdini/custom/USDOP/OBJ_LOPCamera.C: In member function ‘void pxrInternal_v0_19__pxrReserved__::OBJ_LOPCamera::LOPPATH(UT_String&)’:
/XXX/houdiniusdbridge/src/houdini/custom/USDOP/OBJ_LOPCamera.C:173:21: error: ‘lopPathName’ was not declared in this scope
     evalString(str, lopPathName.getToken(),
```

**Houdini version:** 18.0.308
**USD version:** custom 19.11

Same for _houdini18.0_ branch

**Comment by marktucker** [comment]
Houdini 18.0.308 will only build against the devhoudini18.0 branch at the commit intended for that specific release of Houdini, or in this case, the most recent release of Houdini before this one, since there were no changes to this repository specifically for 18.0.308):
https://github.com/sideeffects/HoudiniUsdBridge/commit/4cfa7d0e56f6f84e96567534248b921f65ab2fa4
Although Houdini is continuting to use USD 19.11, Houdini itself marches forward, and this library is tied very tightly to Houdini itself.

**Comment by AlexSchwank** [comment]
OBJ_LOP and OBJ_LOPCamera haven't changed much so I was expecting the same compilation errors in the latest commits. https://github.com/sideeffects/HoudiniUsdBridge/commit/4cfa7d0e56f6f84e96567534248b921f65ab2fa4 is working (after adding _USDFS/CMakeSources.cmake_). Thanks @marktucker .
