### ISSUE TITLE
GEO_FileData: missing ENV_HOUDINI_BGEO_TO_USD_DEFAULT_ARGS

### ISSUE THREAD

**Issue by AlexSchwank** [sideeffects/HoudiniUsdBridge#8]
Trying to compile _master_ gives me this error:
```
/XXX/houdiniusdbridge/src/houdini/custom/USD/GEO_FileData.C: In function ‘bool pxrInternal_v0_19__pxrReserved__::getCookOption(const FileFormatArguments*, const UT_StringRef&, const GU_Detail*, const UT_StringRef&, std::string&)’:
/XXX/houdiniusdbridge/src/houdini/custom/USD/GEO_FileData.C:105:21: error: ‘ENV_HOUDINI_BGEO_TO_USD_DEFAULT_ARGS’ was not declared in this scope
                     ENV_HOUDINI_BGEO_TO_USD_DEFAULT_ARGS)))
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Houdini version:** 18.0.308
**USD version:** custom 19.11

Same for _houdini18.0_ branch

**Comment by marktucker** [comment]
Houdini 18.0.308 will only build against the devhoudini18.0 branch at the commit intended for that specific release of Houdini, or in this case, the most recent release of Houdini before this one, since there were no changes to this repository specifically for 18.0.308):
https://github.com/sideeffects/HoudiniUsdBridge/commit/4cfa7d0e56f6f84e96567534248b921f65ab2fa4
Although Houdini is continuting to use USD 19.11, Houdini itself marches forward, and this library is tied very tightly to Houdini itself.

**Comment by AlexSchwank** [comment]
OBJ_LOP and OBJ_LOPCamera haven't changed much so I was expecting the same compilation errors in the latest commits. https://github.com/sideeffects/HoudiniUsdBridge/commit/4cfa7d0e56f6f84e96567534248b921f65ab2fa4 is working (after adding _USDFS/CMakeSources.cmake_). Thanks @marktucker .

**Comment by marktucker** [comment]
There are a lot of dependencies from HUSD and the plugins here on generic Houdini code all over the place. And we can't feasibly limit our Houdini development to only allow changes that won't prevent this sort of problem. So we have to go with the approach of insisting you use the HoudiniUsdBridge version that exactly matches your Houdini version. It's not ideal, but it's where we are. Glad you got things going when you used the matching HoudiniUsdBridge branch!
